// Generated by CoffeeScript 1.3.3
(function() {
  var AI_Selector, Advanced_Strategy, Basic_Strategy, root;

  Basic_Strategy = require('./basic_strategy').Basic_Strategy;

  Advanced_Strategy = require('./advanced_strategy').Advanced_Strategy;

  AI_Selector = (function() {

    function AI_Selector() {}

    AI_Selector.prototype.select = function(type) {
      switch (type) {
        case "basic":
          return new Basic_Strategy;
        default:
          return new Advanced_Strategy;
      }
    };

    return AI_Selector;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.AI_Selector = AI_Selector;

}).call(this);
