// Generated by CoffeeScript 1.3.3
(function() {
  var Ball, root;

  Ball = (function() {

    function Ball(position, radius) {
      this.position = position;
      this.radius = radius;
      this.speed = 0;
      this.dx = 0;
      this.dy = 0;
    }

    Ball.prototype.update = function(newPosition, dt) {
      this.dx = newPosition.x - this.position.x;
      this.dy = newPosition.y - this.position.y;
      this.position = newPosition;
      return this.speed = this.dx / dt;
    };

    return Ball;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Ball = Ball;

}).call(this);
