// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.log = function(module, text) {
    return console.log("" + module + ": " + text);
  };

}).call(this);
