// Generated by CoffeeScript 1.3.3
(function() {
  var Opponent, root;

  Opponent = (function() {

    function Opponent(y, width, height) {
      this.y = y;
      this.width = width;
      this.height = height;
    }

    Opponent.prototype.update = function(y) {
      this.y = y;
    };

    return Opponent;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Opponent = Opponent;

}).call(this);
