// Generated by CoffeeScript 1.3.3
(function() {
  var AI, AI_Selector, chai, expect;

  AI = require('../src/ai').AI;

  AI_Selector = require('../src/ai_selector').AI_Selector;

  chai = require('chai');

  expect = chai.expect;

  describe('Basic Strategy', function() {
    var ai;
    ai = null;
    beforeEach(function() {
      var selector;
      selector = new AI_Selector;
      return ai = selector.select('basic');
    });
    return it('should just change x-direction when estimating new direction', function() {
      var result, vector;
      vector = {
        x: 30,
        y: 30,
        dx: -3,
        dy: 2
      };
      result = ai.estimateNewDirection(vector);
      return expect(result.dx).to.equal(3);
    });
  });

}).call(this);
