// Generated by CoffeeScript 1.3.3
(function() {
  var Helper, chai, expect;

  Helper = require('../src/helper');

  chai = require('chai');

  expect = chai.expect;

  describe('Helper', function() {
    it('should be able to define the intersection of two lines', function() {
      var point;
      point = Helper.intersect({
        x: 0,
        y: 0
      }, {
        x: 10,
        y: 10
      }, {
        x: 0,
        y: 5
      }, {
        x: 10,
        y: 5
      });
      expect(point.x).to.equal(5);
      return expect(point.y).to.equal(5);
    });
    return it('should calculate balls movement time to wall', function() {
      var time;
      time = Helper.timeToTarget(5, 1, 0);
      return expect(time).to.equal(5);
    });
  });

}).call(this);
