// Generated by CoffeeScript 1.3.3
(function() {
  var Opponent, chai, expect;

  Opponent = require('../src/opponent').Opponent;

  chai = require('chai');

  expect = chai.expect;

  describe('Opponent', function() {
    var opponent;
    opponent = new Opponent(0);
    it('constructing should store position', function() {
      return expect(opponent.y).to.equal(0);
    });
    return it('should update value of y', function() {
      opponent.update(5);
      return expect(opponent.y).to.equal(5);
    });
  });

}).call(this);
